title: anthologyrp wiki
description: wiki for anthologyrp, in the hollows
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  anthology home: https://anthologyrp.tumblr.com
aux_links_new_tab: true

nav_enabled: true

collections_dir: docs
collections:
  cast:
    permalink: "/:collection/:path/"
    output: true
  episodes:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    cast:
      name: Cast
    episodes:
      name: Episodes
